### ISSUE TITLE
Plugin dependency configuration

### ISSUE THREAD

**Issue by cheebo** [nori-io/nori#23]
Plugin can request interfaces from the Registry.

Nori must support:
1. `Registry` can load multiple plugins with the same interface with no error.

For example, 2 plugins implement `nori/Cache` interface. One plugin implements this interface for `reads`, another plugin implements this interfaces for `memcached`. 

It would be great to have opportunity to configure which plugin `Registry` must return on interface request by specific plugin. 

For example, `templates` plugin requests `nori/Cache` interface and receives `memcached` but `sessions` plugin receives `redis` on the same interface request .

Config example:
```yml
plugins: 
  - nori/templates: # plugin id
    - nori/Cache: "nori/redis:2.1.3" # interface: id:version
  - nori/sessions: # plugin id
    - nori/Cache: "nori/memcached:1.0.2" # interface: id:version
```
